# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://dcassol2020.github.io/
title: Dani Cassol
email: danicassol@gmail.com
author: Dani Cassol
description: "Cassol's Personal Page"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
# Build sitemap
plugins:
  - jekyll-sitemap

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - icon: github
    title: github
    url: https://github.com/dcassol 
  - icon: envelope-o
    title: email
    url: mailto:danicassol@gmail.com
  - icon: linkedin
    title: linkedin
    url: https://www.linkedin.com/in/danicassol/
#  - icon: file-pdf-o
#    title: CV
#    url: img/MyCV.pdf
#  - icon: twitter
#    title: twitter
#    url: https://twitter.com/dcassol

